name: LegalEye App CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
      - run: date

      - name: Send email notification
        if: success()
        uses: dawidd6/action-send-mail@v3
        with:
          connection_url: smtp://${{ secrets.SMTP_USER }}:${{ secrets.SMTP_PASSWORD }}@${{ secrets.SMTP_SERVER }}:${{ secrets.SMTP_PORT }}
          subject: 'CI Notification: All Tests Passed'
          to: ${{ secrets.NOTIFICATION_EMAIL }} 
          from: ${{ secrets.SMTP_USER }}
          body: |
            All tests have passed successfully in the Isa Legal App CI workflow.

    concurrency:
      group: "ci-${{ github.ref }}"
      cancel-in-progress: true
